// Generated by CoffeeScript 1.6.2
(function() {
  var i, letters, _i, _len;

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (_i = 0, _len = letters.length; _i < _len; _i++) {
    i = letters[_i];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29tcGlsZS9zdWIvbGV0dGVycy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbImxldHRlcnMuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTtDQUFBLEtBQUEsY0FBQTs7Q0FBQSxDQUFBLENBQVUsSUFBVjs7QUFFQSxDQUFBLE1BQUEsdUNBQUE7cUJBQUE7Q0FBQSxFQUFBLENBQUEsR0FBTztDQUFQLEVBRkE7Q0FBQSJ9