// Generated by CoffeeScript 1.7.1
(function() {
  var i, letters, _i, _len;

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (_i = 0, _len = letters.length; _i < _len; _i++) {
    i = letters[_i];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib3V0cHV0L3N1Yi9sZXR0ZXJzLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibGV0dGVycy5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBO0FBQUEsTUFBQSxvQkFBQTs7QUFBQSxFQUFBLE9BQUEsR0FBVSxDQUFDLEdBQUQsRUFBSyxHQUFMLEVBQVMsR0FBVCxFQUFhLEdBQWIsRUFBaUIsR0FBakIsRUFBc0IsR0FBdEIsQ0FBVixDQUFBOztBQUVBLE9BQUEsOENBQUE7b0JBQUE7QUFBQSxJQUFBLE9BQU8sQ0FBQyxHQUFSLENBQVksQ0FBWixDQUFBLENBQUE7QUFBQSxHQUZBO0FBQUEifQ==