// Generated by CoffeeScript 1.6.2
(function() {
  var i, letters, _i, _len;

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (_i = 0, _len = letters.length; _i < _len; _i++) {
    i = letters[_i];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib3V0cHV0L3N1Yi9sZXR0ZXJzLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibGV0dGVycy5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBO0NBQUEsS0FBQSxjQUFBOztDQUFBLENBQUEsQ0FBVSxJQUFWOztBQUVBLENBQUEsTUFBQSx1Q0FBQTtxQkFBQTtDQUFBLEVBQUEsQ0FBQSxHQUFPO0NBQVAsRUFGQTtDQUFBIn0=