// Generated by CoffeeScript 1.9.2
(function() {
  var i, j, k, l, len, len1, len2, letters, letters2, numbers;

  numbers = [1, 2, 3, 4];

  for (j = 0, len = numbers.length; j < len; j++) {
    i = numbers[j];
    console.log(i);
  }

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (k = 0, len1 = letters.length; k < len1; k++) {
    i = letters[k];
    console.log(i);
  }

  letters2 = ['x', 'y', 'z'];

  for (l = 0, len2 = letters2.length; l < len2; l++) {
    i = letters2[l];
    console.log(i);
  }

}).call(this);
