// Generated by CoffeeScript 1.6.2
(function() {
  var i, letters, letters2, numbers, _i, _j, _k, _len, _len1, _len2;

  numbers = [1, 2, 3, 4];

  for (_i = 0, _len = numbers.length; _i < _len; _i++) {
    i = numbers[_i];
    console.log(i);
  }

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (_j = 0, _len1 = letters.length; _j < _len1; _j++) {
    i = letters[_j];
    console.log(i);
  }

  letters2 = ['x', 'y', 'z'];

  for (_k = 0, _len2 = letters2.length; _k < _len2; _k++) {
    i = letters2[_k];
    console.log(i);
  }

}).call(this);
