// Generated by CoffeeScript 1.6.2
(function() {
  var i, letters, letters2, numbers, _i, _j, _k, _len, _len1, _len2;

  numbers = [1, 2, 3, 4];

  for (_i = 0, _len = numbers.length; _i < _len; _i++) {
    i = numbers[_i];
    console.log(i);
  }

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (_j = 0, _len1 = letters.length; _j < _len1; _j++) {
    i = letters[_j];
    console.log(i);
  }

  letters2 = ['x', 'y', 'z'];

  for (_k = 0, _len2 = letters2.length; _k < _len2; _k++) {
    i = letters2[_k];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiam9pbi5qcyIsInNvdXJjZXMiOlsiY29tcGlsZS9udW1iZXJzLmNvZmZlZSIsImNvbXBpbGUvc3ViL2xldHRlcnMuY29mZmVlIiwiY29tcGlsZS9zdWIvc3Vic3ViL2xldHRlcnMyLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQ0E7Q0FBQSxLQUFBLHVEQUFBOztDQUFBLENBQUEsQ0FBVSxJQUFWOztBQUVBLENBQUEsTUFBQSx1Q0FBQTtxQkFBQTtDQUFBLEVBQUEsQ0FBQSxHQUFPO0NBQVAsRUFGQTs7Q0FBQSxDQ0RBLENBQVUsSUFBVjs7QUFFQSxDQUFBLE1BQUEseUNBQUE7cUJBQUE7Q0FBQSxFQUFBLENBQUEsR0FBTztDQUFQLEVEREE7O0NBQUEsQ0VEQSxDQUFXLEtBQVg7O0FBRUEsQ0FBQSxNQUFBLDBDQUFBO3NCQUFBO0NBQUEsRUFBQSxDQUFBLEdBQU87Q0FBUCxFRkRBO0NBQUEiLCJzb3VyY2VSb290Ijoiam9pbl9tYXBzcmMifQ==