// Generated by CoffeeScript 1.7.1
(function() {
  var i, letters, letters2, numbers, _i, _j, _k, _len, _len1, _len2;

  numbers = [1, 2, 3, 4];

  for (_i = 0, _len = numbers.length; _i < _len; _i++) {
    i = numbers[_i];
    console.log(i);
  }

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (_j = 0, _len1 = letters.length; _j < _len1; _j++) {
    i = letters[_j];
    console.log(i);
  }

  letters2 = ['x', 'y', 'z'];

  for (_k = 0, _len2 = letters2.length; _k < _len2; _k++) {
    i = letters2[_k];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiam9pbi5qcyIsInNvdXJjZXMiOlsiY29tcGlsZS9udW1iZXJzLmNvZmZlZSIsImNvbXBpbGUvc3ViL2xldHRlcnMuY29mZmVlIiwiY29tcGlsZS9zdWIvc3Vic3ViL2xldHRlcnMyLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQ0E7QUFBQSxNQUFBLDZEQUFBOztBQUFBLEVBQUEsT0FBQSxHQUFVLENBQUMsQ0FBRCxFQUFHLENBQUgsRUFBSyxDQUFMLEVBQU8sQ0FBUCxDQUFWLENBQUE7O0FBRUEsT0FBQSw4Q0FBQTtvQkFBQTtBQUFBLElBQUEsT0FBTyxDQUFDLEdBQVIsQ0FBWSxDQUFaLENBQUEsQ0FBQTtBQUFBLEdBRkE7O0FBQUEsRUNEQSxPQUFBLEdBQVUsQ0FBQyxHQUFELEVBQUssR0FBTCxFQUFTLEdBQVQsRUFBYSxHQUFiLEVBQWlCLEdBQWpCLEVBQXNCLEdBQXRCLENEQ1YsQ0FBQTs7QUNDQSxPQUFBLGdEQUFBO29CQUFBO0FBQUEsSUFBQSxPQUFPLENBQUMsR0FBUixDQUFZLENBQVosQ0FBQSxDQUFBO0FBQUEsR0REQTs7QUFBQSxFRURBLFFBQUEsR0FBVyxDQUFDLEdBQUQsRUFBSyxHQUFMLEVBQVMsR0FBVCxDRkNYLENBQUE7O0FFQ0EsT0FBQSxpREFBQTtxQkFBQTtBQUFBLElBQUEsT0FBTyxDQUFDLEdBQVIsQ0FBWSxDQUFaLENBQUEsQ0FBQTtBQUFBLEdGREE7QUFBQSIsInNvdXJjZVJvb3QiOiJqb2luX21hcHNyYyJ9