// Generated by CoffeeScript 1.7.1
(function() {
  var i, letters, _i, _len;

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (_i = 0, _len = letters.length; _i < _len; _i++) {
    i = letters[_i];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibGV0dGVycy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbImxldHRlcnMuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTtBQUFBLE1BQUEsb0JBQUE7O0FBQUEsRUFBQSxPQUFBLEdBQVUsQ0FBQyxHQUFELEVBQUssR0FBTCxFQUFTLEdBQVQsRUFBYSxHQUFiLEVBQWlCLEdBQWpCLEVBQXNCLEdBQXRCLENBQVYsQ0FBQTs7QUFFQSxPQUFBLDhDQUFBO29CQUFBO0FBQUEsSUFBQSxPQUFPLENBQUMsR0FBUixDQUFZLENBQVosQ0FBQSxDQUFBO0FBQUEsR0FGQTtBQUFBIn0=