// Generated by CoffeeScript 1.6.2
(function() {
  var i, numbers, _i, _len;

  numbers = [1, 2, 3, 4];

  for (_i = 0, _len = numbers.length; _i < _len; _i++) {
    i = numbers[_i];
    console.log(i);
  }

}).call(this);
