// Generated by CoffeeScript 1.6.2
(function() {
  var i, numbers, _i, _len;

  numbers = [1, 2, 3, 4];

  for (_i = 0, _len = numbers.length; _i < _len; _i++) {
    i = numbers[_i];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib3V0cHV0L251bWJlcnMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJudW1iZXJzLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQ0E7Q0FBQSxLQUFBLGNBQUE7O0NBQUEsQ0FBQSxDQUFVLElBQVY7O0FBRUEsQ0FBQSxNQUFBLHVDQUFBO3FCQUFBO0NBQUEsRUFBQSxDQUFBLEdBQU87Q0FBUCxFQUZBO0NBQUEifQ==