// Generated by CoffeeScript 1.7.1
(function() {
  var i, numbers, _i, _len;

  numbers = [1, 2, 3, 4];

  for (_i = 0, _len = numbers.length; _i < _len; _i++) {
    i = numbers[_i];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib3V0cHV0L251bWJlcnMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJudW1iZXJzLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQ0E7QUFBQSxNQUFBLG9CQUFBOztBQUFBLEVBQUEsT0FBQSxHQUFVLENBQUMsQ0FBRCxFQUFHLENBQUgsRUFBSyxDQUFMLEVBQU8sQ0FBUCxDQUFWLENBQUE7O0FBRUEsT0FBQSw4Q0FBQTtvQkFBQTtBQUFBLElBQUEsT0FBTyxDQUFDLEdBQVIsQ0FBWSxDQUFaLENBQUEsQ0FBQTtBQUFBLEdBRkE7QUFBQSJ9