// Generated by CoffeeScript 1.10.0
(function() {
  var i, j, len, letters2;

  letters2 = ['x', 'y', 'z'];

  for (j = 0, len = letters2.length; j < len; j++) {
    i = letters2[j];
    console.log(i);
  }

}).call(this);
