// Generated by CoffeeScript 1.6.2
(function() {
  var i, letters2, _i, _len;

  letters2 = ['x', 'y', 'z'];

  for (_i = 0, _len = letters2.length; _i < _len; _i++) {
    i = letters2[_i];
    console.log(i);
  }

}).call(this);
