// Generated by CoffeeScript 1.6.2
(function() {
  var i, letters2, _i, _len;

  letters2 = ['x', 'y', 'z'];

  for (_i = 0, _len = letters2.length; _i < _len; _i++) {
    i = letters2[_i];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29tcGlsZS9zdWIvc3Vic3ViL2xldHRlcnMyLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibGV0dGVyczIuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTtDQUFBLEtBQUEsZUFBQTs7Q0FBQSxDQUFBLENBQVcsS0FBWDs7QUFFQSxDQUFBLE1BQUEsd0NBQUE7c0JBQUE7Q0FBQSxFQUFBLENBQUEsR0FBTztDQUFQLEVBRkE7Q0FBQSJ9