// Generated by CoffeeScript 1.7.1
(function() {
  var i, letters, _i, _len;

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (_i = 0, _len = letters.length; _i < _len; _i++) {
    i = letters[_i];
    console.log(i);
  }

}).call(this);
