// Generated by CoffeeScript 1.10.0
(function() {
  var i, j, len, letters;

  letters = ['a', 'b', 'c', 'd', 'e', 'x'];

  for (j = 0, len = letters.length; j < len; j++) {
    i = letters[j];
    console.log(i);
  }

}).call(this);
