// Generated by CoffeeScript 1.7.1
(function() {
  var i, letters2, _i, _len;

  letters2 = ['x', 'y', 'z'];

  for (_i = 0, _len = letters2.length; _i < _len; _i++) {
    i = letters2[_i];
    console.log(i);
  }

}).call(this);

//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib3V0cHV0L3N1Yi9zdWJzdWIvbGV0dGVyczIuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJsZXR0ZXJzMi5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBO0FBQUEsTUFBQSxxQkFBQTs7QUFBQSxFQUFBLFFBQUEsR0FBVyxDQUFDLEdBQUQsRUFBSyxHQUFMLEVBQVMsR0FBVCxDQUFYLENBQUE7O0FBRUEsT0FBQSwrQ0FBQTtxQkFBQTtBQUFBLElBQUEsT0FBTyxDQUFDLEdBQVIsQ0FBWSxDQUFaLENBQUEsQ0FBQTtBQUFBLEdBRkE7QUFBQSJ9